collector {
  streams {
  
    //New object-like style
    good = ${collector.streams.sink} 
    bad = ${collector.streams.sink} 
    
    //Legacy style
    sink {
      maxBytes = ${snowplow.defaults.sinks.kafka.maxRecordSize}
      buffer = ${collector.streams.buffer}
      producerConf = ${snowplow.defaults.sinks.kafka.producerConf}
      producerConf = {
        "client.id": "snowplow-collector"
      }
      startupCheckInterval = "10 seconds"
      retryInterval = "10 seconds"
    }

    //Legacy style
    buffer {
      byteLimit = 3145728
      recordLimit = 500
      timeLimit = 5000
    }
   }
}
