dist: trusty
language: scala
scala:
- 2.12.2
jdk:
- openjdk8
script:
- sbt compile
deploy:
- provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: Mji3yBHICZemRAl1dUsr9cOZC6t5FDPxxUCSI3ISGOj1HreTQGnSLGOlu+k+HWtqLb93S0B3HrjJ1Vp+HL42OreTze1kjXDO/nhIje7f6BIjK1wGrFs8xnKIDNkq+ZV27+5X/beG6SIFK1p6yuvfxfK6Nne/WwbcpRcntGgWlGZ+OY6rXN9UfRaOXu6J8HbrOlk3OfkQoEvbIykmxnGgznnZP8oRV5blglnK6X+OMDUJVtYtYsQ59AGfqiXtiTbT87LNrkngp3P+gBqtnf/q4A6R4aeRnIkJKF7KktXPx7efbN0Q0YJIhfY1NdUHuZMlnNdkTFHKDXGa3oz/CPLaXtpZbkPlq/DOYTgJvwbsRVx83umeY/elzuV9S0oK4DFLOshKR8g57qjx+Lm53vvTqPP8yLpWtF27/bSGVRMhZGDzWSYk0vVJj8Axd643mVC6e7shx+SDv6qu5GX2m6lVysdmDfNiWc/kASc/gASFCU6PyV8Mi5VD3fyixRIBrZOmsUgSmHlHIf/Rd+I0wVTQS0RaswaPshL90GbVhgQQuIy8Sx7iDlTKWqkRsWn7wLQ24JrjACbOtUNSYyiag0Reb00nKN7suJokfOMU190CQkCVS9rXJkTmwH0V5Qm/rVTFqD1xgiLbu+WXwSAWmqhOk/Pd0PcgPYiaMJY5oKmEW1I=
  - secure: KaD2dRhAMwV92vqKSsUgc9JPFj8RVYPK7S9ouH1b0LqlDanNoDT+PuCMcT9le4cpjIzOUbdVyJBdzTg+AFRowictegfZhC64bU2IUMW7uUO/GY+8+na0B3GwvSl9bLLvbX7rgs2lFt+d+4x8djmW6OMBOZXXDL7N8aaPI6TigcsHkgevzqKRWqditq7Qfk4svrI3nwlpIYjmdnEBeb8GxvyRqHUMLhxaz6tp6cR+F0eQI0cMDcRx9LNRfkTUPclwyOXbdJE8KvYHBObOm5NXotG0eY7Y1JXp1Bar3Qo4ELo4mqMGvb1mUNHrpJjyCjJj8YKRsNwEImJqn9rLyn6pldzhzJCpEEs7hEgjPxLN7m+ZB7h8dh+h2fsxr+rnbDvdsCJD7xnj4ogeNknhGx5PC9KBuOy9jSIXr5CGs8axp7Bun6fZjW4ZNpZtZi3e/F3O7uW+NlWs5MnohrfJi1ZSwUuMxflFkG2rM9y8fCsX34lhVrZenasH7q5PQBGo3kzXSy6XYsDPllSIbqD86bVU4Hy4kz3xxSf9oxj2K4P1E+JkqJux2TXXi/Jvgdbq0AlqcVADSmlIkmNQgb+bbvadwIOuOLpSqapuCVB81VFIk/QLDao9rupPKd3OyaYKENufnaQp+Z13LAtPtjpfe6rxQNWmSCXsYh9QizVxVnB5dJY=
