package com.snowplowanalytics.snowplow.collector.core

import scala.concurrent.duration._
import scala.annotation.tailrec
import java.nio.{ByteBuffer, ByteOrder}

import org.http4s.SameSite

import com.snowplowanalytics.snowplow.collector.core.Config.{Sink => SinkConfig, _}

object TestUtils {
  val appName    = "collector-test"
  val appVersion = "testVersion"

  val appInfo = new AppInfo {
    def name        = appName
    def moduleName  = appName
    def version     = appVersion
    def dockerAlias = "docker run collector"
    def sinkName    = "test"
  }

  val testConfig = Config[Any](
    interface = "0.0.0.0",
    port      = 8080,
    paths = Map(
      "/com.acme/track"    -> "/com.snowplowanalytics.snowplow/tp2",
      "/com.acme/redirect" -> "/r/tp2",
      "/com.acme/iglu"     -> "/com.snowplowanalytics.iglu/v1"
    ),
    p3p = P3P(
      "/w3c/p3p.xml",
      "NOI DSP COR NID PSA OUR IND COM NAV STA"
    ),
    crossDomain = CrossDomain(
      false,
      List("*"),
      true
    ),
    cookie = Cookie(
      enabled          = true,
      name             = "sp",
      expiration       = 365.days,
      domains          = Nil,
      fallbackDomain   = None,
      secure           = true,
      httpOnly         = true,
      sameSite         = Some(SameSite.None),
      clientCookieName = None
    ),
    doNotTrackCookie = DoNotTrackCookie(
      false,
      "",
      ""
    ),
    cookieBounce = CookieBounce(
      false,
      "n3pc",
      "00000000-0000-4000-A000-000000000000",
      None
    ),
    redirectMacro = RedirectMacro(
      false,
      None
    ),
    rootResponse = RootResponse(
      false,
      302,
      Map.empty[String, String],
      ""
    ),
    cors = CORS(60.minutes),
    streams = Streams(
      good = SinkConfig(
        name = "raw",
        Buffer(
          3145728,
          500,
          5000
        ),
        AnyRef
      ),
      bad = SinkConfig(
        name = "bad-1",
        Buffer(
          3145728,
          500,
          5000
        ),
        AnyRef
      )
    ),
    monitoring = Monitoring(
      Metrics(
        Statsd(
          false,
          "localhost",
          8125,
          10.seconds,
          "snowplow.collector",
          Map.empty
        )
      )
    ),
    ssl = SSL(
      false,
      false,
      443
    ),
    hsts = HSTS(
      false,
      365.days
    ),
    networking = Networking(
      1024,
      610.seconds,
      30.seconds,
      25.seconds,
      20480,
      40960,
      1048576,
      2097152
    ),
    enableDefaultRedirect = false,
    redirectDomains       = Set.empty[String],
    preTerminationPeriod  = 10.seconds,
    telemetry = Config.Telemetry(
      disable         = false,
      interval        = 60.minutes,
      method          = "POST",
      url             = "telemetry-g.snowplowanalytics.com",
      port            = 443,
      secure          = true,
      userProvidedId  = None,
      moduleName      = None,
      moduleVersion   = None,
      instanceId      = None,
      autoGeneratedId = None
    ),
    license = License(accept = true),
    compression = Config.Compression(
      enabled              = false,
      `type`               = Config.Compression.ZSTD,
      gzipCompressionLevel = 6,
      zstdCompressionLevel = 9
    )
  )

  /** Parse records from decompressed binary data with compression/payload format headers */
  def parseRecords(decompressed: Array[Byte]): Either[String, List[Array[Byte]]] =
    if (decompressed.length < 2) {
      Left("Data too short: need at least 2 bytes for headers")
    } else if (decompressed(0) != 1 || decompressed(1) != 1) {
      Left(s"Invalid headers: expected [1,1], got [${decompressed(0)},${decompressed(1)}]")
    } else {
      @tailrec
      def go(offset: Int, records: List[Array[Byte]]): Either[String, List[Array[Byte]]] =
        if (offset == decompressed.length) {
          // Successfully consumed all data
          Right(records.reverse)
        } else if (offset > decompressed.length) {
          Left(s"Offset $offset exceeds data length ${decompressed.length}")
        } else if (offset + 4 > decompressed.length) {
          Left(s"Not enough bytes for size header at offset $offset")
        } else {
          // Read 4-byte size header (big-endian)
          val size       = ByteBuffer.wrap(decompressed, offset, 4).order(ByteOrder.BIG_ENDIAN).getInt()
          val dataOffset = offset + 4

          if (size < 0) {
            Left(s"Invalid record size: $size at offset $offset")
          } else if (dataOffset + size > decompressed.length) {
            Left(s"Record size $size at offset $offset exceeds remaining data")
          } else {
            // Extract record data
            val record = decompressed.slice(dataOffset, dataOffset + size)
            go(dataOffset + size, record :: records)
          }
        }

      go(2, Nil)
    }
}
