/**
 * Copyright (c) 2013-present Snowplow Analytics Ltd.
 * All rights reserved.
 *
 * This program is licensed to you under the Snowplow Community License Version 1.0,
 * and you may not use this file except in compliance with the Snowplow Community License Version 1.0.
 * You may obtain a copy of the Snowplow Community License Version 1.0 at https://docs.snowplow.io/community-license-1.0
 */
package com.snowplowanalytics.snowplow.collectors.scalastream.telemetry

// iglu:com.snowplowanalytics.oss/oss_context/jsonschema/1-0-1
private case class TelemetryPayload(
  userProvidedId: Option[String]  = None,
  moduleName: Option[String]      = None,
  moduleVersion: Option[String]   = None,
  instanceId: Option[String]      = None,
  region: Option[String]          = None,
  cloud: Option[CloudVendor]      = None,
  autoGeneratedId: Option[String] = None,
  applicationName: String,
  applicationVersion: String,
  appGeneratedId: String
)
