addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"        % "0.10.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.17")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"           % "4.1.1")
addSbtPlugin("com.snowplowanalytics"     % "sbt-snowplow-release" % "0.3.2")
