addSbtPlugin("com.eed3si9n"              % "sbt-assembly"         % "0.15.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager"  % "1.3.25")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"        % "0.10.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.17")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"           % "4.1.1")
