name: test

on: push

jobs:
  test:
    if: ${{ github.event.repository.private == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Install Thrift
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libthrift-java thrift-compiler
          version: 1.0
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Run unit tests
        run: sbt +test
      - name: Run integration tests Kinesis
        run: sbt "project kinesisDistroless" IntegrationTest/test
      - name: Run integration tests PubSub
        run: sbt "project pubsubDistroless" IntegrationTest/test
      - name: Run integration tests Kafka
        run: sbt "project kafkaDistroless" IntegrationTest/test
